root: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:react/recommended
  - plugin:react-hooks/recommended
settings: {react: {version: detect}}
rules:
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  'react/prop-types': off
  'react/react-in-jsx-scope': off
  'no-restricted-syntax':
    - error
    - message: Use `setCookie` instead of `cookies.set`
      selector: CallExpression[callee.object.name='cookies'][callee.property.name='set']
    - message: Use `newCookies` instead of `new Cookies`
      selector: NewExpression[callee.name='Cookies']
overrides:
  - files: ['*.js']
    env: {node: true}
    rules:
      '@typescript-eslint/no-var-requires': off
  - files: ['*.tsx']
    rules:
      '@typescript-eslint/explicit-module-boundary-types': off
